### ISSUE TITLE
Mrgsolve to SBML conversion

### ISSUE THREAD

**Issue by Jomigi** [hetalang/heta-compiler#21]
Colleagues and I at the Dutch National Institute for Public Health and the Environment are working on developing a workflow to automatically convert ODE-models developed in various software environments (e.g. Mrgsolve) to the SBML format. We came across your heta package and were very interested since it already supports the conversion in the opposite direction, from SBML to various software environment. Thus, we were wondering if there are any future plans to extend the heta compiler to also support the conversion from the various software environments, in particular Mrgsolve, to SBML. If not, do you have maybe have any suggestions of existing packages that support the conversion from Mrgsolve to SBML? 

Best,
Jordi

**Comment by metelkin** [comment]
Good day.
The main problem of conversion of Mrgsolve to SBML or Heta is that there are two different approaches to describe the dynamic systems: ODE based and process-based. Mrgsolve is totally ODE-based while the rest are process-based.
There are strict rules to translate from process-based to ODE but not backwards.
More sophisticated algorithms translating ODE to Species, Compartments, Reactions (as it required for Heta/SBML) are possible but only for limited set of Mrgsolve models. It also need mrgsolve format parser which need much time to implement. I guess it is out of our scope.

Unfortunately I know no tools for this issue. Let me know if you find one. Did you ask @kylebaron who is the key developer of Mrgsolve?

**Comment by kylebaron** [comment]
Hi @Jomigi  - 

I agree with @metelkin's response on this: there isn't a tool to do this conversion now and I think it's unlikely. To do that, you'd have to write a parser to take apart the mrgsolve model code and that could potentially be very complex. We could programmatically extract some aspects of the models, but getting rules and reactions would probably be beyond our scope as well. I think if you want this kind of interconversion, you have to go the other direction like @metelkin does with heta.

Best regards,
Kyle Baron

**Comment by Jomigi** [comment]
Hi @metelkin @kylebaron, thank you very much for your responses! In that case we will look into some other options.
