### ISSUE TITLE
Exported Matlab model does not run

### ISSUE THREAD

**Issue by eltix** [hetalang/heta-compiler#22]
## Issue description

After converting an SBML model to Matlab with
```
pnpm heta-build --type sbml --source SBMLModel.xml --export Matlab
```
the model does not run in Matlab because of the following error:
```
Error using ismember (line 84)
First argument must be text.

Error in nameless_run (line 42)
[idx, loc] = ismember(show_ids, output_ids);
```
which points to this part of the generated Matlab code:
```
%  list of record to plot
show_ids = [];

% plot records
figure
hold on
[idx, loc] = ismember(show_ids, output_ids);
```

Indeed, `[]` is interpreted here as a list of `double` values instead of the expected list of `string`.
Setting a non-empty list for `show_ids` fixes the issue, such as 
```
show_ids = ["DefaultComp_DOT_Precursor"];
```
for instance

### Proposals

  a. `show_ids` could be set with the content of `output_ids` or a subset of it such that the model runs out of the box.
  b. or the user error should be made more explicit, perhaps by checking for the emptiness of `show_ids` before calling `ismember` and then returning something like "show_ids must be a non-empty subset of output_ids".

### Packages

  * Matlab: `24.2.0.2790852 (R2024b) Update 2`
  * heta-compiler: `0.9.1`

**Comment by metelkin** [comment]
I agree, an empty list of outputs should not result in error.
It seems like the easiest way to fix it, is to forcely set the type of array, like `string([])` It will result to emty plot.
It will be in the next release.

**Comment by eltix** [comment]
Thank you @metelkin! Indeed casting `show_ids` as a `[string]` seems to be the best solution.
