### ISSUE TITLE
Fails importing valid SBML document

### ISSUE THREAD

**Issue by eltix** [hetalang/heta-compiler#23]
## Issue description

```xml
<?xml version="1.0" encoding="UTF-8"?>
<sbml xmlns="http://www.sbml.org/sbml/level3/version2/core" level="3" version="2">
  <model id="Apoptosis" name="Apoptosis" timeUnits="second" extentUnits="mole">
    <listOfParameters>
      <parameter id="foo" units="dimensionless" constant="true"/>
    </listOfParameters>
    <listOfInitialAssignments>
      <initialAssignment symbol="foo">
        <math xmlns="http://www.w3.org/1998/Math/MathML">
          <apply>
            <times/>
            <cn> 3 </cn>
            <cn> 2 </cn>
          </apply>
        </math>
      </initialAssignment>
    </listOfInitialAssignments>
  </model>
</sbml>
```

The above SBML document fails to be imported in heta which produces the following error:
```
[error]	No required "num" property for "foo" of Const.
```

However, the document is valid. My understanding is that `heta` complains that `"foo"` has `constant=true` while having no `value` attribute set, the value being set by an `InitialAssignment`. This is however valid per the SBML L3V2 specifications.

### Packages

  * heta-compiler: `0.9.1`

**Comment by metelkin** [comment]
Yes, you interpretation seems correct. There is a mismatch between SBML and Heta formats.
Maybe it should be imported as 
```
foo @Record { units: dimensionless,  boundary: true} .= 3 * 2;
```
but now 
```
foo @Const { units: dimensionless };
```

**Comment by metelkin** [comment]
add fix as above. Will be published in new release
