### ISSUE TITLE
SBML avogadro unit not accepted by heta

### ISSUE THREAD

**Issue by eltix** [hetalang/heta-compiler#24]
## Issue description

```xml
<?xml version="1.0" encoding="UTF-8"?>
<sbml xmlns="http://www.sbml.org/sbml/level3/version2/core" level="3" version="2">
  <model id="Apoptosis" name="Apoptosis" timeUnits="second" extentUnits="mole">
    <listOfParameters>
      <parameter id="foo" units="avogadro" constant="true" value = "1"/>
    </listOfParameters>
  </model>
</sbml>
```

The above SBML document fails to be imported in heta which produces the following error:
```
[error]	UnitDef "avogadro" is not found as expected here: foo { units: avogadro };
```

However, `avogadro` is a valid unit identifier per the [SBML L3V2 specs](https://sbml.org/specifications/sbml-level-3/version-2/core/release-1/sbml-level-3-version-2-core.pdf#subsubsection.4.4.2)

### Packages

  * heta-compiler: `0.9.1`

**Comment by metelkin** [comment]
Thanks for letting us know, the fix is done. It will published in the next release

**Comment by eltix** [comment]
Thanks @metelkin
